document.addEventListener('DOMContentLoaded', () => {
            // Seleciona os elementos da página
                const revealButton = document.getElementById('revealButton');
                    const proposalSection = document.getElementById('proposalSection');
                        const yesButton = document.getElementById('yesButton');
                            const noButton = document.getElementById('noButton');
                                const responseMessageDiv = document.getElementById('responseMessage');
                                    const h1Element = document.querySelector('h1'); // Seleciona o h1 inicial
                                        const paragraphs = document.querySelectorAll('p'); // Seleciona todos os parágrafos
                                            const mainImage = document.querySelector('.main-image'); // Seleciona a imagem principal


                                                // Função para tocar a música (se você tiver uma)
                                                    function playMusic() {
                                                            // Crie um elemento de áudio
                                                                    const audio = new Audio('assets/sua-musica.mp3');
                                                                            audio.loop = true; // Para a música tocar em loop
                                                                                    audio.volume = 0.7; // Ajuste o volume (0.0 a 1.0)
                                                                                            
                                                                                                    // Tente tocar a música. Alguns navegadores bloqueiam autoplay sem interação do usuário.
                                                                                                            // Se falhar, você pode adicionar um botão "Tocar música" para ela clicar.
                                                                                                                    audio.play().catch(error => {
                                                                                                                                console.log("Autoplay de áudio bloqueado. Considere adicionar um botão de play.", error);
                                                                                                                                            // Opcional: Adicionar um botão na tela para tocar a música
                                                                                                                                                        // const musicButton = document.createElement('button');
                                                                                                                                                                    // musicButton.textContent = "Tocar música fofa";
                                                                                                                                                                                // musicButton.addEventListener('click', () => audio.play());
                                                                                                                                                                                            // document.body.appendChild(musicButton);
                                                                                                                                                                                                    });
                                                                                                                                                                                                        }

                                                                                                                                                                                                            // Evento ao clicar no botão "Clique aqui para descobrir!"
                                                                                                                                                                                                                revealButton.addEventListener('click', () => {
                                                                                                                                                                                                                        // Esconde os elementos iniciais suavemente
                                                                                                                                                                                                                                h1Element.style.opacity = '0';
                                                                                                                                                                                                                                        h1Element.style.transform = 'translateY(-20px)';
                                                                                                                                                                                                                                                paragraphs.forEach(p => {
                                                                                                                                                                                                                                                            p.style.opacity = '0';
                                                                                                                                                                                                                                                                        p.style.transform = 'translateY(-20px)';
                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                        mainImage.style.opacity = '0';
                                                                                                                                                                                                                                                                                                mainImage.style.transform = 'scale(0.8)';
                                                                                                                                                                                                                                                                                                        revealButton.style.opacity = '0';
                                                                                                                                                                                                                                                                                                                revealButton.style.transform = 'translateY(20px)';

                                                                                                                                                                                                                                                                                                                        // Atraso para a transição dos elementos iniciais
                                                                                                                                                                                                                                                                                                                                setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                            revealButton.classList.add('hidden'); // Esconde o botão de revelar
                                                                                                                                                                                                                                                                                                                                                        // Mostra a seção da pergunta com uma animação
                                                                                                                                                                                                                                                                                                                                                                    proposalSection.classList.remove('hidden'); 
                                                                                                                                                                                                                                                                                                                                                                                proposalSection.style.animation = 'popIn 0.6s ease-out forwards';
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                        // Tocar música quando a pergunta for revelada
                                                                                                                                                                                                                                                                                                                                                                                                                    playMusic(); 

                                                                                                                                                                                                                                                                                                                                                                                                                            }, 800); // Tempo para as animações de esconder terminarem
                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                    // Evento ao clicar no botão "SIM! 😍"
                                                                                                                                                                                                                                                                                                                                                                                                                                        yesButton.addEventListener('click', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                proposalSection.classList.add('hidden'); // Esconde a seção da pergunta
                                                                                                                                                                                                                                                                                                                                                                                                                                                        responseMessageDiv.classList.remove('hidden'); // Mostra a seção de resposta

                                                                                                                                                                                                                                                                                                                                                                                                                                                                responseMessageDiv.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2>AAAAAH! QUE FELICIDADE! 😍</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>Você me fez a pessoa mais feliz do mundo! Mal posso esperar para viver muitas coisas cntg ( e fzr mts sapecagens tbm, hehehehe😈)</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <img src="assets/confetes.gif" alt="Confetes caindo" style="max-width: 100%; margin-top: 20px; border-radius: 10px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p style="margin-top: 20px; font-size: 1.2em; font-weight: bold;">Eu te amo princesa!</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                responseMessageDiv.style.animation = 'fadeIn 1s forwards'; // Anima a mensagem de resposta
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Evento ao clicar no botão "Não (só se for de brincadeira 😉)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            noButton.addEventListener('click', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                      